name: move_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bottom_bar: ^1.3.0+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  uses-material-design: true
